### ISSUE TITLE
Get appoitments by slot of times

### ISSUE THREAD

**Issue by cecicasco** [iHub-PTI/ihub-core#12]
Get the list of  appointments of a doctor, specifying start and end time

**Comment by rubenlop88** [comment]
I added a "start" and "end" query params to all the GET /appointments endpoints. If present, the lists return all the appointments with a starting date and time greater than "start" and less than "end".

**Comment by pA1nD** [comment]
Do I understand correctly that we can call /appointments?start=ISODate?

This also works in the /profile/*/appointments endpoints.

**Comment by rubenlop88** [comment]
Yes. That's how it should work. Let me know if you have any issues. The date format must be the same es the one in the appointment object.
