### ISSUE TITLE
Add pagination to doctors search endpoint

### ISSUE THREAD

**Issue by pA1nD** [iHub-PTI/ihub-core#24]
There should be pagination on the doctors search endpoint.

Suggested default value: 30 objects per page.

**Comment by rubenlop88** [comment]
The latest version of HAPI FHIR, 5.2.0, released last month, adds support for "stateless" pagination, but it is not standard FHIR. The FHIR standard only specifies that the server must return a link to the next page. In the case of HAPI FHIR, that link contains a uuid that identifies the request, and must be provided again to the server to obtain the next page. With the new "_offset" param it is now possible to construct the next page link without the server generated id.

**Comment by rubenlop88** [comment]
FHIR has a default page size, for example 20. If the result of a query has more than 20 items, FHIR returns some metadata containing the total number of items and some links to fetch the previous and next pages.

How should we handle this on our API? We are currently returning a list of all the items, without any metadata about the list. Should we add the metadata in the body of the response? Or maybe in a response header?

Currently we have:

```
GET /doctors

[
  { doctor1... }, 
  { doctor2...}, 
  ...
]
```

We could change it to:

```
GET /doctors

{
  total: ...,
  count: ...,
  offset: ...,
  list: [
    { doctor1... }, 
    { doctor2...}, 
    ...
  ],
  ...
}
```

Or:

```
GET /doctors
Header1: ...
Header2: ...

[
  { doctor1... }, 
  { doctor2...}, 
  ...
]
```

I've never done it with headers before. I don't know which header names would be appropriate.
